application: destinyclantest
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /profile/profileStatic
  static_dir: static
  
- url: /static
  static_dir: static
  
- url: /clanPage/clanStatic
  static_dir: static
  
- url: /profile
  script: profile/profile.php
  
- url: .*
  script: clanPage/main.php

